{
 "title": "Location_Based_Recommendations",
 "description": "Main dashboard for location based recommendation demo",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Stores visitors",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "valueName": "total",
   "targets": [
    { "target": "[object Object]", "type": "table" }
   ]
  },
  {
   "title": "Recommended Products",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none", "label": "# Recommended" }
   ],
   "targets": [
    { "target": "product", "type": "timeserie" }
   ]
  },
  {
   "title": "Prediction Confidence",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "prediction", "type": "timeserie" }
   ]
  },
  {
   "title": "Latest Predictions",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "targets": [
    { "target": "user_id", "type": "timeserie" },
    { "target": "product", "type": "timeserie" },
    { "target": "prediction_num", "type": "timeserie" },
    { "target": "prediction", "type": "timeserie" }
   ]
  }
 ]
}