{
 "title": "Location_Based_Recommendations",
 "description": "Main dashboard for location based recommendation demo",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Stores visitors",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "valueName": "current",
   "targets": [
    { "target": "[object Object]", "type": "table" }
   ]
  },
  {
   "title": "Times recommended (Per Product)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Times Recommended" }
   ],
   "targets": [
    {
     "target": "backend=tsdb;container=bigdata;start=now-1h;query=select count(prediction) times  from predictions group by product_id",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Prediction Confidence",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "backend=tsdb;container=bigdata;start=now-1h;query=select avg(prediction) as prediction_avg from predictions group by prediction_num",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Latest Predictions",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "target": "backend=tsdb;container=bigdata;start=now-1m;query=select customer_id, store, product_id, prediction_num, prediction from predictions limit 20",
     "type": "table"
    }
   ]
  }
 ]
}